export const PROJECT_TONES = {
  pink: {
    card: "bg-pink", num: "text-rose", chip: "bg-ink/[.08] text-plum",
    title: "text-maroon", body: "text-maroon/78", tag: "bg-cream/70 text-plum",
    btn: "bg-ink text-cream", icon: "bg-cream/15 text-cream",
    ghost: "bg-cream/75 border-ink/15 text-plum", ghostIcon: "bg-plum/10 text-plum",
    rule: "border-maroon/25", kicker: "text-maroon/50",
    stat: "bg-cream", statNum: "text-maroon", statLabel: "text-maroon/52",
    todo: "bg-cream/45 border-maroon/30 text-maroon/55",
    mediaBg: "bg-cocoa", mediaDot: "#F6DDE0",
    slotBorder: "border-cream/30", slotText: "text-cream/60",
    slotFill: "repeating-linear-gradient(135deg,rgba(255,253,247,.12) 0 9px,rgba(255,253,247,.03) 9px 18px)",
  },
  teal: {
    card: "bg-teal", num: "text-pink", chip: "bg-cream/[.16] text-mint-light",
    title: "text-mint-light", body: "text-mint-light/85", tag: "bg-cream/[.14] text-mint-light",
    btn: "bg-cream text-teal-dark", icon: "bg-teal-dark/10 text-teal-dark",
    ghost: "bg-cream/[.16] border-cream/30 text-mint-light", ghostIcon: "bg-cream/20 text-mint-light",
    rule: "border-mint-light/20", kicker: "text-mint-light/55",
    stat: "bg-cream/[.12]", statNum: "text-cream", statLabel: "text-mint-light/60",
    todo: "bg-cream/5 border-mint-light/35 text-mint-light/60",
    mediaBg: "bg-teal-deep", mediaDot: "rgba(246,221,224,.14)",
    slotBorder: "border-cream/30", slotText: "text-cream/60",
    slotFill: "repeating-linear-gradient(135deg,rgba(255,253,247,.12) 0 9px,rgba(255,253,247,.03) 9px 18px)",
  },
  blue: {
    card: "bg-blue", num: "text-cream", chip: "bg-navy-soft/15 text-navy-soft",
    title: "text-navy", body: "text-navy/82", tag: "bg-cream/60 text-navy-soft",
    btn: "bg-navy text-cream", icon: "bg-cream/15 text-cream",
    ghost: "bg-cream/70 border-navy/15 text-navy-soft", ghostIcon: "bg-navy-soft/10 text-navy-soft",
    rule: "border-navy/25", kicker: "text-navy/55",
    stat: "bg-cream", statNum: "text-navy", statLabel: "text-navy/52",
    todo: "bg-cream/50 border-navy/30 text-navy/55",
    mediaBg: "bg-blue-pale", mediaDot: "rgba(143,184,216,.85)",
    slotBorder: "border-navy/30", slotText: "text-navy/60",
    slotFill: "repeating-linear-gradient(135deg,rgba(18,40,58,.1) 0 9px,rgba(18,40,58,.03) 9px 18px)",
  },
} as const;
